services:
  - type: web
    name: shopping-list-app
    runtime: docker
    dockerfilePath: ./shopping-list/Dockerfile
    envVars:
      - key: MODE
        value: production
      - key: PORT
        value: 7777
      - key: BASE_URL
        value: http://localhost:7777
      - key: DATABASE_URL
        fromDatabase:
          name: shopping-list-db  # Référence à la base de données existante
          property: connectionString
    autoDeploy: true
    plan: starter
    healthCheckPath: /

  - type: cron  # Cron job pour exécuter les migrations Flyway
    name: flyway-migration
    runtime: docker
    dockerfilePath: ./flyway/Dockerfile
    schedule: "@daily"  # Exécute les migrations quotidiennement (ou choisis une autre fréquence)
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shopping-list-db  # Référence à la base de données existante
          property: connectionString
      - key: PG_PROD_USER
        value: PG_PROD_USER # Tu pourras définir cela dans Render
      - key: PG_PROD_PASSWORD
        value: PG_PROD_PASSWORD  # Tu pourras définir cela dans Render
    plan: starter

databases:
  - name: shopping-list-db
    plan: starter
    region: oregon
