services:
  - type: web
    name: shopping-list-app
    runtime: docker
    dockerfilePath: ./shopping-list/Dockerfile
    startCommand: npm run start
    envVars:
      - key: MODE
        value: production
      - key: PORT
        value: 7777
      - key: BASE_URL
        value: http://localhost:7777
      - key: DATABASE_URL
        fromDatabase:
          name: shopping-list-db
          property: connectionString
    autoDeploy: true
    plan: starter
    healthCheckPath: /

  - type: cron  # Job pour exécuter les migrations Flyway
    name: flyway-migration
    runtime: docker
    dockerfilePath: ./flyway/Dockerfile
    schedule: "@onstart"  # Exécute les migrations à chaque démarrage
    startCommand: >
      flyway -url=jdbc:postgresql://${DATABASE_URL} -user=${FLYWAY_USER} -password=${FLYWAY_PASSWORD} migrate
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shopping-list-db
          property: connectionString
      - key: FLYWAY_USER
        value: ${PG_PROD_USER}  # Tu pourras définir cela dans Render
      - key: FLYWAY_PASSWORD
        value: ${PG_PROD_PASSWORD}  # Tu pourras définir cela dans Render
    plan: starter

databases:
  - name: shopping-list-db
    databaseName: ${PG_PROD_DB}
    user: ${PG_PROD_USER}
    plan: starter
    region: oregon